name: /gpfs/fs0/scratch/s/shreejoy/nxu/trap_seq/envs/trap_seq
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - amply=0.1.6=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argcomplete=3.3.0=pyhd8ed1ab_0
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - binutils_impl_linux-64=2.40=ha885e6a_0
  - bioconductor-annotationdbi=1.64.1=r43hdfd78af_0
  - bioconductor-apeglm=1.24.0=r43hf17093f_1
  - bioconductor-biobase=2.62.0=r43ha9d7317_2
  - bioconductor-biocfilecache=2.10.1=r43hdfd78af_0
  - bioconductor-biocgenerics=0.48.1=r43hdfd78af_2
  - bioconductor-biocio=1.12.0=r43hdfd78af_0
  - bioconductor-biocparallel=1.36.0=r43hf17093f_2
  - bioconductor-biomart=2.58.0=r43hdfd78af_0
  - bioconductor-biostrings=2.70.1=r43ha9d7317_2
  - bioconductor-data-packages=20231203=hdfd78af_0
  - bioconductor-delayedarray=0.28.0=r43ha9d7317_2
  - bioconductor-deseq2=1.42.0=r43hf17093f_1
  - bioconductor-genomeinfodb=1.38.1=r43hdfd78af_1
  - bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
  - bioconductor-genomicalignments=1.38.0=r43ha9d7317_0
  - bioconductor-genomicfeatures=1.54.1=r43hdfd78af_0
  - bioconductor-genomicranges=1.54.1=r43ha9d7317_2
  - bioconductor-iranges=2.36.0=r43ha9d7317_2
  - bioconductor-keggrest=1.42.0=r43hdfd78af_0
  - bioconductor-matrixgenerics=1.14.0=r43hdfd78af_3
  - bioconductor-rhtslib=2.4.0=r43ha9d7317_2
  - bioconductor-rsamtools=2.18.0=r43hf17093f_1
  - bioconductor-rtracklayer=1.62.0=r43ha9d7317_0
  - bioconductor-s4arrays=1.2.0=r43ha9d7317_2
  - bioconductor-s4vectors=0.40.2=r43ha9d7317_2
  - bioconductor-sparsearray=1.2.2=r43ha9d7317_2
  - bioconductor-summarizedexperiment=1.32.0=r43hdfd78af_0
  - bioconductor-tximport=1.30.0=r43hdfd78af_1
  - bioconductor-xvector=0.42.0=r43ha9d7317_2
  - bioconductor-zlibbioc=1.48.0=r43ha9d7317_2
  - brotli-python=1.1.0=py312h30efb56_1
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.10=haf5fa05_0
  - coin-or-utils=2.11.11=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda-inject=1.3.1=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - curl=8.7.1=hca28451_0
  - datrie=0.8.2=py312h98912ed_7
  - docutils=0.21.2=pyhd8ed1ab_0
  - dpath=2.1.6=pyha770c72_0
  - eido=0.2.2=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - expat=2.6.2=h59595ed_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.2.0=h9eb54c0_7
  - gfortran_impl_linux-64=13.2.0=h738fc78_7
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - graphite2=1.3.13=h59595ed_1003
  - gxx_impl_linux-64=13.2.0=h2a599c4_7
  - harfbuzz=8.4.0=h3d44ed6_0
  - humanfriendly=10.0=pyhd8ed1ab_6
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - immutables=0.20=py312h98912ed_1
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jq=1.7.1=hd590300_0
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libcurl=8.7.1=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=hceb6213_107
  - libgcc-ng=13.2.0=h77fa898_7
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.0=hf2295e7_6
  - libgomp=13.2.0=h77fa898_7
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=22_linux64_openblas
  - liblapacke=3.9.0=22_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libsanitizer=13.2.0=h6ddb7a1_7
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=hceb6213_107
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_2
  - libzlib=1.2.13=hd590300_5
  - logmuse=0.2.6=pyh8c360ce_0
  - make=4.3=hd18ef5c_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312h98912ed_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - numpy=1.26.4=py312heda63a1_0
  - oniguruma=6.9.9=hd590300_0
  - openssl=3.3.0=hd590300_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py312hfb8ada1_0
  - pandoc=3.1.13=ha770c72_0
  - pango=1.52.2=ha41ecd1_0
  - pcre2=10.43=hcad00b1_0
  - peppy=0.40.1=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.3=pyhd8ed1ab_0
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - psutil=5.9.8=py312h98912ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.8.0=py312h7900ff3_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.2.0=pyhd8ed1ab_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - r-abind=1.4_5=r43hc72bb7e_1005
  - r-ashr=2.2_63=r43ha503ecb_0
  - r-askpass=1.2.0=r43h57805ef_0
  - r-assertthat=0.2.1=r43hc72bb7e_4
  - r-backports=1.4.1=r43h57805ef_2
  - r-base=4.3.3=hf0d99cb_1
  - r-base64enc=0.1_3=r43h57805ef_1006
  - r-bbmle=1.0.25.1=r43hc72bb7e_0
  - r-bdsmatrix=1.3_7=r43h57805ef_0
  - r-bh=1.84.0_0=r43hc72bb7e_0
  - r-biocmanager=1.30.23=r43hc72bb7e_0
  - r-bit=4.0.5=r43h57805ef_1
  - r-bit64=4.0.5=r43h57805ef_2
  - r-bitops=1.0_7=r43h57805ef_2
  - r-blob=1.2.4=r43hc72bb7e_1
  - r-brew=1.0_10=r43hc72bb7e_0
  - r-broom=1.0.5=r43hc72bb7e_1
  - r-bslib=0.7.0=r43hc72bb7e_0
  - r-cachem=1.0.8=r43h57805ef_1
  - r-callr=3.7.6=r43hc72bb7e_0
  - r-cellranger=1.1.0=r43hc72bb7e_1006
  - r-cli=3.6.2=r43ha503ecb_0
  - r-clipr=0.8.0=r43hc72bb7e_2
  - r-coda=0.19_4.1=r43hc72bb7e_0
  - r-codetools=0.2_20=r43hc72bb7e_0
  - r-collections=0.3.7=r43h57805ef_1
  - r-colorspace=2.1_0=r43h57805ef_1
  - r-commonmark=1.9.1=r43h57805ef_0
  - r-conflicted=1.2.0=r43h785f33e_1
  - r-cpp11=0.4.7=r43hc72bb7e_0
  - r-crayon=1.5.2=r43hc72bb7e_2
  - r-curl=5.1.0=r43hf9611b0_0
  - r-cyclocomp=1.1.1=r43hc72bb7e_0
  - r-data.table=1.15.2=r43h029312a_0
  - r-dbi=1.2.2=r43hc72bb7e_0
  - r-dbplyr=2.5.0=r43hc72bb7e_0
  - r-desc=1.4.3=r43hc72bb7e_0
  - r-digest=0.6.35=r43ha503ecb_0
  - r-dplyr=1.1.4=r43ha503ecb_0
  - r-dtplyr=1.3.1=r43hc72bb7e_1
  - r-ellipsis=0.3.2=r43h57805ef_2
  - r-emdbook=1.3.13=r43hc72bb7e_0
  - r-etrunct=0.1=r43hc72bb7e_1005
  - r-evaluate=0.23=r43hc72bb7e_0
  - r-fansi=1.0.6=r43h57805ef_0
  - r-farver=2.1.1=r43ha503ecb_2
  - r-fastmap=1.1.1=r43ha503ecb_1
  - r-filelock=1.0.3=r43h57805ef_0
  - r-fontawesome=0.5.2=r43hc72bb7e_0
  - r-forcats=1.0.0=r43hc72bb7e_1
  - r-formatr=1.14=r43hc72bb7e_1
  - r-fs=1.6.4=r43ha18555a_0
  - r-futile.logger=1.4.3=r43hc72bb7e_1005
  - r-futile.options=1.0.1=r43hc72bb7e_1004
  - r-gargle=1.5.2=r43h785f33e_0
  - r-generics=0.1.3=r43hc72bb7e_2
  - r-ggplot2=3.5.1=r43hc72bb7e_0
  - r-glue=1.7.0=r43h57805ef_0
  - r-googledrive=2.1.1=r43hc72bb7e_1
  - r-googlesheets4=1.1.1=r43h785f33e_1
  - r-gtable=0.3.5=r43hc72bb7e_0
  - r-haven=2.5.4=r43ha503ecb_0
  - r-here=1.0.1=r43hc72bb7e_2
  - r-highr=0.10=r43hc72bb7e_1
  - r-hms=1.1.3=r43hc72bb7e_1
  - r-htmltools=0.5.8.1=r43ha503ecb_0
  - r-httr=1.4.7=r43hc72bb7e_0
  - r-ids=1.0.1=r43hc72bb7e_3
  - r-invgamma=1.1=r43hc72bb7e_3
  - r-irlba=2.3.5.1=r43h316c678_1
  - r-isoband=0.2.7=r43ha503ecb_2
  - r-jquerylib=0.1.4=r43hc72bb7e_2
  - r-jsonlite=1.8.8=r43h57805ef_0
  - r-knitr=1.46=r43hc72bb7e_0
  - r-labeling=0.4.3=r43hc72bb7e_0
  - r-lambda.r=1.2.4=r43hc72bb7e_3
  - r-languageserver=0.3.16=r43h57805ef_0
  - r-lattice=0.22_6=r43h57805ef_0
  - r-lazyeval=0.2.2=r43h57805ef_4
  - r-lifecycle=1.0.4=r43hc72bb7e_0
  - r-lintr=3.1.2=r43hc72bb7e_0
  - r-locfit=1.5_9.9=r43h57805ef_0
  - r-lubridate=1.9.3=r43h57805ef_0
  - r-magrittr=2.0.3=r43h57805ef_2
  - r-mass=7.3_60=r43h57805ef_1
  - r-matrix=1.6_5=r43h316c678_0
  - r-matrixstats=1.3.0=r43h57805ef_0
  - r-memoise=2.0.1=r43hc72bb7e_2
  - r-mgcv=1.9_1=r43h316c678_0
  - r-mime=0.12=r43h57805ef_2
  - r-mixsqp=0.3_54=r43h08d816e_0
  - r-modelr=0.1.11=r43hc72bb7e_1
  - r-munsell=0.5.1=r43hc72bb7e_0
  - r-mvtnorm=1.2_4=r43hd9ac46e_0
  - r-nlme=3.1_164=r43h61816a4_0
  - r-numderiv=2016.8_1.1=r43hc72bb7e_5
  - r-openssl=2.1.2=r43hd7d0243_0
  - r-pillar=1.9.0=r43hc72bb7e_1
  - r-pkgbuild=1.4.4=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_3
  - r-pkgload=1.3.4=r43hc72bb7e_0
  - r-plogr=0.2.0=r43hc72bb7e_1005
  - r-plyr=1.8.9=r43ha503ecb_0
  - r-png=0.1_8=r43h81d01c5_1
  - r-prettyunits=1.2.0=r43hc72bb7e_0
  - r-processx=3.8.4=r43h57805ef_0
  - r-progress=1.2.3=r43hc72bb7e_0
  - r-ps=1.7.6=r43h57805ef_0
  - r-purrr=1.0.2=r43h57805ef_0
  - r-r.cache=0.16.0=r43hc72bb7e_2
  - r-r.methodss3=1.8.2=r43hc72bb7e_2
  - r-r.oo=1.26.0=r43hc72bb7e_0
  - r-r.utils=2.12.3=r43hc72bb7e_0
  - r-r6=2.5.1=r43hc72bb7e_2
  - r-ragg=1.3.0=r43h73ae6e3_0
  - r-rappdirs=0.3.3=r43h57805ef_2
  - r-rcolorbrewer=1.1_3=r43h785f33e_2
  - r-rcpp=1.0.12=r43h7df8631_0
  - r-rcpparmadillo=0.12.8.2.1=r43h08d816e_0
  - r-rcppeigen=0.3.4.0.0=r43h08d816e_0
  - r-rcppnumerical=0.6_0=r43ha503ecb_0
  - r-rcurl=1.98_1.14=r43hf9611b0_0
  - r-readr=2.1.5=r43ha503ecb_0
  - r-readxl=1.4.3=r43ha5c9fba_0
  - r-rematch=2.0.0=r43hc72bb7e_0
  - r-rematch2=2.1.2=r43hc72bb7e_3
  - r-remotes=2.5.0=r43hc72bb7e_0
  - r-repr=1.1.7=r43h785f33e_0
  - r-reprex=2.1.0=r43hc72bb7e_0
  - r-restfulr=0.0.15=r43h56115f1_3
  - r-rex=1.2.1=r43hc72bb7e_2
  - r-rjson=0.2.21=r43ha503ecb_3
  - r-rlang=1.1.3=r43ha503ecb_0
  - r-rmarkdown=2.26=r43hc72bb7e_0
  - r-roxygen2=7.3.1=r43ha503ecb_0
  - r-rprojroot=2.0.4=r43hc72bb7e_0
  - r-rsqlite=2.3.4=r43ha503ecb_0
  - r-rstudioapi=0.16.0=r43hc72bb7e_0
  - r-rvest=1.0.4=r43hc72bb7e_0
  - r-sass=0.4.9=r43ha503ecb_0
  - r-scales=1.3.0=r43hc72bb7e_0
  - r-selectr=0.4_2=r43hc72bb7e_3
  - r-snow=0.4_4=r43hc72bb7e_2
  - r-squarem=2021.1=r43hc72bb7e_2
  - r-stringi=1.8.4=r43hbd1cc82_0
  - r-stringr=1.5.1=r43h785f33e_0
  - r-styler=1.10.3=r43hc72bb7e_0
  - r-sys=3.4.2=r43h57805ef_1
  - r-systemfonts=1.0.5=r43haf97adc_0
  - r-textshaping=0.3.7=r43hd87b9d6_0
  - r-tibble=3.2.1=r43h57805ef_2
  - r-tidyr=1.3.1=r43ha503ecb_0
  - r-tidyselect=1.2.1=r43hc72bb7e_0
  - r-tidyverse=2.0.0=r43h785f33e_1
  - r-timechange=0.3.0=r43ha503ecb_0
  - r-tinytex=0.50=r43hc72bb7e_0
  - r-truncnorm=1.0_9=r43h57805ef_1
  - r-tzdb=0.4.0=r43ha503ecb_1
  - r-utf8=1.2.4=r43h57805ef_0
  - r-uuid=1.2_0=r43h57805ef_0
  - r-vctrs=0.6.5=r43ha503ecb_0
  - r-viridislite=0.4.2=r43hc72bb7e_1
  - r-vroom=1.6.5=r43ha503ecb_0
  - r-withr=3.0.0=r43hc72bb7e_0
  - r-xfun=0.43=r43ha503ecb_0
  - r-xml=3.99_0.16.1=r43hc6530ce_0
  - r-xml2=1.3.6=r43hbfba7a4_1
  - r-xmlparsedata=1.0.5=r43hc72bb7e_2
  - r-yaml=2.3.8=r43h57805ef_0
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rpds-py=0.18.0=py312h4b3b743_0
  - sed=4.8=he412f7d_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slack-sdk=3.27.1=pyha770c72_0
  - slack_sdk=3.27.1=hd8ed1ab_0
  - smart_open=7.0.4=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=8.11.3=hdfd78af_0
  - snakemake-executor-plugin-slurm=0.4.5=pyhdfd78af_0
  - snakemake-executor-plugin-slurm-jobstep=0.2.1=pyhdfd78af_0
  - snakemake-interface-common=1.17.2=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.1.1=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.0.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=3.2.2=pyhdfd78af_0
  - snakemake-minimal=8.11.3=pyhdfd78af_0
  - stopit=1.1.2=py_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tabulate=0.9.0=pyhd8ed1ab_1
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.4=pyha770c72_0
  - toposort=1.10=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ubiquerg=0.7.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wrapt=1.16.0=py312h98912ed_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yq=3.4.3=pyhd8ed1ab_0
  - yte=1.5.4=pyha770c72_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
prefix: /gpfs/fs0/scratch/s/shreejoy/nxu/trap_seq/envs/trap_seq
